// <auto-generated />
using System;
using ApiProject.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiProject.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("ApiProject.Domain.PhoneCases.PhoneCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Model")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<short>("Sold")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PhoneCases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Green",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImgUrl = "https://ae-pic-a1.aliexpress-media.com/kf/S0082d2ca5c48496c8df2d0b69a3edaddq.jpg_960x960q75.jpg_.avif",
                            Model = 1,
                            Name = "Shockproof Armor Matte Case",
                            Price = 81.0,
                            Sold = (short)0,
                            Stock = (short)10
                        },
                        new
                        {
                            Id = 2,
                            Color = "Black",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImgUrl = "https://ae-pic-a1.aliexpress-media.com/kf/S10f49ffaa7ea434ca62700fa04444087l.jpg_960x960q75.jpg_.avif",
                            Model = 4,
                            Name = "Luxury Liquid Silicone Phone Case ",
                            Price = 92.0,
                            Sold = (short)0,
                            Stock = (short)10
                        },
                        new
                        {
                            Id = 3,
                            Color = "Red Brown",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImgUrl = "https://ae-pic-a1.aliexpress-media.com/kf/S4fc26c62c8104b288029a0852d1117cc6.jpg_960x960q75.jpg_.avif",
                            Model = 4,
                            Name = "Luxury Liquid Silicone For Magsafe Phone Case",
                            Price = 255.0,
                            Sold = (short)0,
                            Stock = (short)10
                        });
                });

            modelBuilder.Entity("ApiProject.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@caseshop.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEOMiV4vZOmimSUP3whM3EdotmdNNlNiPUySw18aeStR3+nVzltjeGeoRqT93FbCtVw==",
                            Role = "Admin",
                            Username = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
